name: Tests, Coverage and GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # Needed for badge commit
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest==7.4.0 pytest-cov==4.1.0 coverage==7.3.2 genbadge[coverage]

      - name: Run tests with coverage
        continue-on-error: true  # Continue workflow even if tests fail
        run: |
          mkdir -p site
          python -m pytest --cov=ezstitcher \
                --cov-report=xml \
                --cov-report=html:site/coverage \
                tests/ || echo "Some tests failed, but continuing with coverage report generation"

      - name: Generate coverage badge
        run: |
          mkdir -p .github/badges
          genbadge coverage -i coverage.xml -o .github/badges/coverage.svg -n "coverage report"

      - name: Create index.html and README
        run: |
          # Create index.html for redirection
          cat > site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=./coverage/">
              <title>Redirecting to coverage report...</title>
            </head>
            <body>
              <p>Redirecting to coverage report... <a href="./coverage/">Click here if not redirected</a></p>
            </body>
          </html>
          EOF

          # Create README.md in the site directory
          cat > site/README.md << 'EOF'
          # EZStitcher Code Coverage Reports

          This site contains the code coverage reports for the [EZStitcher](https://github.com/trissim/ezstitcher) project.

          ## Navigation

          - [Coverage Report](./coverage/): View the HTML coverage report

          ## About

          These reports are automatically generated by GitHub Actions whenever changes are pushed to the main branch.
          They show the percentage of code that is covered by automated tests.

          Last updated: $(date)
          EOF

      - name: Commit and push if coverage badge changed
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/coverage.svg
          git commit -m "chore: update coverage badge" || exit 0
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        timeout-minutes: 10
