name: Tests and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write  # Needed for badge commit
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest pytest-cov coverage genbadge[coverage]
          
      - name: Run tests with coverage
        run: |
          mkdir -p site
          pytest --cov=ezstitcher \
                --cov-report=xml \
                --cov-report=html:site/coverage \
                tests/
      
      - name: Generate coverage badge
        run: |
          mkdir -p .github/badges
          genbadge coverage -i coverage.xml -o .github/badges/coverage.svg -n "coverage report"
                
      - name: Create index.html
        run: |
          cat > site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=./coverage/">
              <title>Redirecting to coverage report...</title>
            </head>
            <body>
              <p>Redirecting to coverage report... <a href="./coverage/">Click here if not redirected</a></p>
            </body>
          </html>
          EOF
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Commit and push if coverage badge changed
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/coverage.svg
          git commit -m "chore: update coverage badge" || exit 0
          git push
          
      - name: Upload Pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
          retention-days: 1

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        timeout-minutes: 10