---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest pytest-cov coverage genbadge[coverage]

      - name: Run tests with coverage
        run: |
          pytest --cov=ezstitcher \
                --cov-report=xml \
                tests/

      - name: Generate coverage badge
        run: |
          mkdir -p .github/badges
          genbadge coverage -i coverage.xml -o .github/badges/coverage.svg

      - name: Commit and push if coverage has changed
        run: |
          git config --local user.email \
            "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/coverage.svg
          git commit -m "chore: update coverage badge" || exit 0
          git push
