---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest pytest-cov coverage

      - name: Run tests with coverage
        run: |
          mkdir -p coverage
          pytest --cov=ezstitcher \
                --cov-report=xml \
                --cov-report=json \
                tests/
          coverage json -o coverage/coverage-summary.json

      - name: Get coverage percentage
        run: |
          COV=$(node -p '
            const data = require("./coverage/coverage-summary.json");
            const totals = data.totals;
            Math.floor(totals.percent_covered || totals.line_rate * 100)
          ')
          echo "COVERAGE=$COV" >> $GITHUB_ENV

      - name: Coverage Badge
        uses: we-cli/coverage-badge-action@v1.0.1
        with:
          badges-directory: .github/badges
          coverage: ${{ env.COVERAGE }}

      - name: Commit and push if coverage has changed
        run: |
          git config --local user.email \
            "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/coverage.svg
          git commit -m "chore: update coverage badge" || exit 0
          git push
